pointslog/pl-oss

- libs/adapter/package.json
- libs/domain-core/package.json
- libs/vue-core/package.json
> Version updated

- libs/domain-core/src/lib/aggregate-repository.spec.ts
> Aggregate repository test updated for event sequence test

- libs/domain-core/src/lib/aggregate-repository.spec.ts
- libs/domain-core/src/lib/aggregate.spec.ts
- libs/domain-core/src/lib/event-listener.spec.ts
- libs/domain-core/src/test-domain/index.ts
- libs/domain-core/src/test-domain/test.aggregate-repository.ts
- libs/domain-core/src/test-domain/test.aggregate.ts
- libs/domain-core/src/test-domain/test.event-listener.ts
- libs/domain-core/src/test-domain/test.event.ts
- package.json
- yarn.lock
> Tests Cleanup

- libs/adapter/package.json
- libs/adapter/src/index.ts
- libs/adapter/src/lib/event-store-db/event-store-db.event-store.spec.ts
- libs/adapter/src/lib/event-store-db/event-store-db.event-subscription.spec.ts
- libs/adapter/src/lib/in-memory/in-memory.entity-repository.ts
- libs/adapter/src/lib/mongo-db/mongo-db.entity-repository.ts
- libs/domain-core/package.json
- libs/domain-core/src/index.ts
- libs/domain-core/src/lib/domain-context.ts
- libs/vue-core/package.json
Added
- `DomainContext`
- `InMemoryEntityRepository`
> InMemoryEntityRepository added

- CHANGELOG.md
- libs/adapter/package.json
- libs/domain-core/package.json
- libs/domain-core/src/lib/domain-context.ts
- libs/vue-core/package.json
> Add aggregateRepositoryMap to domain-context

- CHANGELOG.md
- libs/adapter/package.json
- libs/domain/package.json
- libs/vue/package.json
> Release v0.0.21

- libs/vue/babel.config.json
- libs/vue/jest.config.js
- package.json
- yarn.lock
There are some unwanted comments showing up in the tests. Here is a screenshot from the release CI.
> Patch for Vue tests

- CHANGELOG.md
- libs/adapter/index.ts
- libs/adapter/mongo-db/mongo-db.helper.spec.ts
- libs/adapter/mongo-db/mongo-db.helper.ts
- libs/adapter/package.json
- libs/domain/package.json
- libs/vue/package.json
> Add MongoDBHelper

- CHANGELOG.md
- libs/adapter/nest/message/message.controller.spec.ts
- libs/adapter/package.json
- libs/domain/lib/command.ts
- libs/domain/lib/query.ts
- libs/domain/package.json
- libs/vue/package.json
> refactor: by in Command and Query

- .gitignore
- CHANGELOG.md
- libs/adapter/index.ts
- libs/adapter/mongo-db/mongo-db.logger-service.spec.ts
- libs/adapter/mongo-db/mongo-db.logger-service.ts
- libs/adapter/package.json
- libs/domain/package.json
- libs/vue/package.json
> feat: add mongo-db logger-service

- .eslintrc.json
- .gitignore
- .npmignore
- CHANGELOG.md
- libs/adapter/event-store-db/event-store-db.event-subscription.spec.ts
- libs/adapter/event-store-db/event-store-db.event-subscription.ts
- libs/adapter/nest/message/message.controller.spec.ts
- libs/adapter/package.json
- libs/domain/lib/aggregate-repository.ts
- libs/domain/lib/aggregate.ts
- libs/domain/lib/command.ts
- libs/domain/lib/event-listener.ts
- libs/domain/lib/query.ts
- libs/domain/package.json
- libs/domain/test-domain/test.aggregate-repository.ts
- libs/domain/test-domain/test.aggregate.ts
- libs/domain/test-domain/test.event-listener.ts
- libs/vue/component/pl-file-form.vue
- libs/vue/package.json
> Aggregate stream name

- CHANGELOG.md
- libs/adapter/index.ts
- libs/adapter/mongo-db/mongo-db.logger-service.spec.ts
- libs/adapter/mongo-db/mongo-db.logging-service.ts
- libs/adapter/package.json
- libs/domain/index.ts
- libs/domain/lib/context.ts
- libs/domain/lib/logging-service.ts
- libs/domain/package.json
- libs/vue/package.json
> refactor: rename logger-service to logging-service

- CHANGELOG.md
- libs/adapter/mongo-db/mongo-db.logger-service.spec.ts
- libs/adapter/nest/message/message.controller.spec.ts
- libs/adapter/nest/message/message.controller.ts
- libs/adapter/nest/message/message.module.ts
- libs/adapter/package.json
- libs/domain/lib/context.ts
- libs/domain/lib/event.ts
- libs/domain/package.json
- libs/domain/test-domain/test.event.ts
- libs/vue/package.json
> 88 use loggin service

- CHANGELOG.md
- libs/adapter/package.json
- libs/domain/lib/context.ts
- libs/domain/package.json
- libs/vue/component/pl-file-form.vue
- libs/vue/component/pl-text-form.vue
- libs/vue/package.json
- package.json
- yarn.lock
> 97 add slot

- CHANGELOG.md
- libs/adapter/package.json
- libs/domain/package.json
- libs/vue/component/pl-textarea-form.vue
- libs/vue/package.json
- fix: extend `pl-textarea-form` style and class
> fix: extend pl-textarea-form style and class

- CHANGELOG.md
- libs/adapter/package.json
- libs/domain/lib/aggregate.ts
- libs/domain/package.json
- libs/vue/package.json
> Refactor apply to on

- CHANGELOG.md
- libs/adapter/package.json
- libs/domain/package.json
- libs/vue/guard/auth0.guard.ts
- libs/vue/guard/ethers.guard.ts
- libs/vue/index.ts
- libs/vue/package.json
- libs/vue/plugin/auth0.plugin.ts
- libs/vue/plugin/ethers.plugin.ts
- package.json
- yarn.lock
> feat(vue): add ethers-plugin and ethers-guard

- CHANGELOG.md
- libs/adapter/package.json
- libs/domain/package.json
- libs/file-context/package.json
- libs/vue/guard/metamask.guard.ts
- libs/vue/index.ts
- libs/vue/package.json
- libs/vue/plugin/auth0.plugin.ts
- libs/vue/plugin/metamask.plugin.ts
- package.json
- yarn.lock
> feat(vue): add metamask-plugin and metamask-guard

- .github/workflows/prepare.yml
- .github/workflows/publish.yml
- CHANGELOG.md
- libs/adapter/nest/message/message.controller.ts
- libs/adapter/package.json
- libs/core/index.ts
- libs/core/lib/handler-map.ts
- libs/core/lib/query-handler.ts
- libs/core/lib/query.ts
- libs/core/package.json
- libs/vue/package.json
- package.json
> refactor: remove query and handler

- CHANGELOG.md
- libs/adapter/package.json
- libs/core/index.ts
- libs/core/lib/file-entity.helper.ts
- libs/core/lib/id-should-be-unique.exception.ts
- libs/core/lib/invalid-file-extension.exception.ts
- libs/core/lib/unimplemented.exception.ts
- libs/core/package.json
- libs/vue/package.json
> resolve: refactor: add determineExtension method to FileEntityHelper

- CHANGELOG.md
- libs/adapter/package.json
- libs/core/package.json
- libs/vue/guard/metamask.guard.ts
- libs/vue/package.json
- libs/vue/plugin/metamask.plugin.ts
> refactor: explicit login method for metamask plugin

- CHANGELOG.md
- libs/adapter/entity-repository/mongo-db-event-log.ts
- libs/adapter/eth/eth-graphql-auth-service.ts
- libs/adapter/file-store/url-file-store.ts
- libs/adapter/nest/eth-graphql-auth-resolver.ts
- libs/adapter/nest/eth-jwt-strategy.ts
- libs/adapter/package.json
- libs/core/lib/eth-auth-service.ts
- libs/core/lib/event.ts
- libs/core/package.json
- libs/vue/package.json
> feat: add-id-to-event

- libs/vue/plugin/metamask-plugin.ts
Hotfix followup for https://github.com/pointslog/pl-oss/pull/176
> refactor: eth graphql auth service import

- CHANGELOG.md
- libs/adapter/package.json
- libs/core/package.json
- libs/vue/index.ts
- libs/vue/package.json
- libs/vue/service/dom-helper.ts
> feat: add DomHelper
